module.exports = {
    dark: {
        palette: {
            themePrimary: '#309fff',
            themeLighterAlt: '#02060a',
            themeLighter: '#081929',
            themeLight: '#0f304d',
            themeTertiary: '#1d5f99',
            themeSecondary: '#2b8ce0',
            themeDarkAlt: '#45a8ff',
            themeDark: '#62b6ff',
            themeDarker: '#8bc9ff',
            neutralLighterAlt: '#3c3c3c',
            neutralLighter: '#444444',
            neutralLight: '#515151',
            neutralQuaternaryAlt: '#595959',
            neutralQuaternary: '#5f5f5f',
            neutralTertiaryAlt: '#7a7a7a',
            neutralTertiary: '#c8c8c8',
            neutralSecondary: '#d0d0d0',
            neutralPrimaryAlt: '#dadada',
            neutralPrimary: '#ffffff',
            neutralDark: '#f4f4f4',
            black: '#f8f8f8',
            white: '#1b1a19',
        },
        background: '#222222'
    },
    light: {
        palette: {
            themePrimary: '#0078d4',
            themeLighterAlt: '#eff6fc',
            themeLighter: '#deecf9',
            themeLight: '#c7e0f4',
            themeTertiary: '#71afe5',
            themeSecondary: '#2b88d8',
            themeDarkAlt: '#106ebe',
            themeDark: '#005a9e',
            themeDarker: '#004578',
            neutralLighterAlt: '#faf9f8',
            neutralLighter: '#f3f2f1',
            neutralLight: '#edebe9',
            neutralQuaternaryAlt: '#e1dfdd',
            neutralQuaternary: '#d0d0d0',
            neutralTertiaryAlt: '#c8c6c4',
            neutralTertiary: '#a19f9d',
            neutralSecondary: '#605e5c',
            neutralPrimaryAlt: '#3b3a39',
            neutralPrimary: '#323130',
            neutralDark: '#201f1e',
            black: '#000000',
            white: '#ffffff',
        },
        background: '#ffffff'
    }
}